# Generated by Django 4.2.20 on 2025-04-19 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_postlikes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='author',
        ),
        migrations.AddField(
            model_name='postcomments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
