# Generated by Django 4.2.20 on 2025-04-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_postcomments_author_postcomments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.posts'),
        ),
    ]
